### ISSUE TITLE
No engine for Linux?

### ISSUE THREAD

**Issue by marcopiraccini** [grumpygamer/DeloresDev#28]
Hi, tnx for sharing this. I love your work (since I was a kid). 
However, I have only linux laptops at home, can you please, please, please, build the engine also for linux?

(I can help, but obviously I don't have the sources)

**Comment by eikesauer** [comment]
According to [](https://steamcommunity.com/app/1305720/discussions/0/2246677986017458955/) ...

_Once the engine is mature and used in a full game, Linux and other ports will come._

**Comment by marcopiraccini** [comment]
OK, I thought was just a matter of building with a different target. However, according with the link you shared @eikesauer, should work on proton, I'll give a try if I don't have any other option.

**Comment by grumpygamer** [comment]
Unfortunately an Linux build is not s simple as building to a different platform.  It will come but probably not for a few months.
